[project]
name = "sxpb"
version = "0.0.1"
description = "S-expression protobuf data."
readme = "README.md"
license = { text = "0BSD" }
authors = [
  { name = "Alex Klinkhamer", email = "about.sxpb@grencez.dev" }
]
requires-python = ">=3.9"
dependencies = [
    "lark>=1.2.2",
]

[project.urls]
Homepage = "https://github.com/sxpb/sxpb-py"
Repository = "https://github.com/sxpb/sxpb-py"
Issues = "https://github.com/sxpb/sxpb-py/issues"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
addopts = "-v"
pythonpath = ["src"]
testpaths = ["test"]

[project.scripts]
sxpb2json = "sxpb.sxpb2json_main:main"
json2sxpb = "sxpb.json2sxpb_main:main"
sxpb2xml = "sxpb.sxpb2xml_main:main"

[tool.pdm]
package-dir = "src"

[tool.pdm.dev-dependencies]
dev = [
  "pytest",
  "ruff",
  "ty",
]

[tool.pdm.scripts]
check-format = "ruff check"
check-type = "ty check"
tidy = "ruff format"
lint = {composite = ["check-format", "check-type"]}
test = "pytest"

