[project]
name = "sxpb"
version = "0.0.2"
description = "S-expression protobuf data."
readme = "README.md"
license = { text = "0BSD" }
authors = [
  { name = "Alex Klinkhamer", email = "about.sxpb@grencez.dev" }
]
requires-python = ">=3.9"
dependencies = [
    "lark>=1.2.2",
    "pathspec>=0.12.1",
]

[project.urls]
Homepage = "https://github.com/sxpb/sxpb-py"
Repository = "https://github.com/sxpb/sxpb-py"
Issues = "https://github.com/sxpb/sxpb-py/issues"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
addopts = "-v"
pythonpath = ["src", "test"]
testpaths = ["test"]

[project.scripts]
json2sxpb = "sxpb.json2sxpb_main:main"
sxpb2json = "sxpb.sxpb2json_main:main"
sxpb2sxpb = "sxpb.sxpb2sxpb_main:main"
sxpb2xml = "sxpb.sxpb2xml_main:main"
sxpb-tidy = "sxpb.sxpb_tidy_main:main"
sxpb-lint = "sxpb.sxpb_lint_main:main"

[tool.pdm]
package-dir = "src"

[tool.pdm.dev-dependencies]
dev = [
  "pytest",
  "ruff",
  "ty",
]

[tool.pdm.scripts]
check-format = "ruff check"
check-type = "ty check"
lint-sxpb = "sxpb-lint --ignore-file .gitignore"
tidy-python = "ruff format"
tidy-sxpb = "sxpb-tidy --ignore-file .gitignore"
tidy = {composite = ["tidy-python", "tidy-sxpb"]}
lint = {composite = ["check-format", "check-type", "lint-sxpb"]}
test = "pytest"
tidytest = {composite = ["tidy", "lint", "test"]}

[tool.ty.environment]
root = ["src", "test"]
